name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:        # allow manual trigger

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render API
        run: curl -s https://saran-bfhl-api-bajaj.onrender.com/bfhl
